FROM   ubuntu
RUN   apt update
RUN   apt install net-tools openssh-server vim -y
RUN   mkdir /var/run/sshd
RUN   echo 'root:pdxf' |chpasswd
RUN   sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN   sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN   mkdir /root/.ssh
EXPOSE   22
CMD   ["/usr/sbin/sshd", "-D"]
